x-default: &default
  restart: unless-stopped
  networks:
    - overlay
  env_file:
    - .env

x-py-build: &py-build
  build:
    context: .
    dockerfile: Dockerfile

x-heathcheck-interval: &hc-interval
  interval: 2s
  retries: 10
  timeout: 10s

x-celery-default: &celery-default
  << : [ *default, *py-build ]
  depends_on:
    backend:
      condition: service_healthy

x-celery-worker-default: &celery-worker-default
  <<: *celery-default
  healthcheck:
    <<: *hc-interval
    test: [ "CMD-SHELL", "python -m celery inspect ping -d celery@$$HOSTNAME" ]


services:
  postgres:
    <<: *default
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      <<: *hc-interval
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]

  redis:
    <<: *default
    image: redis:7.0
    ports:
      - "6379:6379"
    healthcheck:
      <<: *hc-interval
      test: [ "CMD-SHELL", "redis-cli", "ping" ]

  init_backend:
    << : [*default, *py-build]
    restart: on-failure:5
    command: ["python", "manage.py", "migrate"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  backend:
    << : [*default, *py-build]
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    healthcheck:
      <<: *hc-interval
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/healthcheck/ || exit 1" ]
    depends_on:
      init_backend:
        condition: service_completed_successfully

  celery_default:
    <<: *celery-worker-default
    command: [ "python", "-m", "celery", "-A", "config", "worker", "-Q", "default", "-l", "info" ]

  celery_mass_email_send:
    <<: *celery-worker-default
    command: [ "python", "-m", "celery", "-A", "config", "worker", "-Q", "mass_send_email", "--concurrency", "2", "-l", "info" ]

  celery_beat:
    <<: *celery-default
    command: [ "python", "-m", "celery", "-A", "config", "beat" ]

  celery_flower:
    <<: *celery-default
    ports:
      - "5555:5555"
    command: [ "python", "-m", "celery", "-A", "config", "flower" ]
    healthcheck:
      <<: *hc-interval
      test: [ "CMD-SHELL", "curl --fail http://localhost:5555/metrics || exit 1" ]

volumes:
  db_data:

networks:
  overlay:
