# Generated by Django 4.2.3 on 2023-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.CharField(max_length=256)),
                ('recipient', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Error')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
